name: build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          cd chatbridgee

          zip -r chatbridgee * || echo "build to zip error"
          mv chatbridgee.zip chatbridgee.mcdr
          cp chatbridgee.mcdr ..

          cd ..
          mkdir -p tmp/server && cp -R server tmp
          cp __main__.py tmp/__main__.py
          cd tmp && zip -r server.pyz * && cp server.pyz .. && cd ..

          cd plugins
          zip -r plugins * || echo "build to zip e rror"
          cp plugins.zip ..

      - name: upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: develop
          artifacts: '*.mcdr,*.pyz,*.zip'

      - name: update ref
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Action
          user_email: action@github.com
        run: |
          git config --global user.name "$user_name"
          git config --global user.email "$user_email"

          git remote add origin https://"$token"@github.com/${{ github.event.repository.full_name }}
          git tag -f develop; git push -f origin develop
