name: build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          cd chatbridgee

          zip -r chatbridgee * || echo "build to zip error"
          mv chatbridgee.zip chatbridgee.mcdr
          cp chatbridgee.mcdr ..

          cd ../server
          zip -r server * || echo "build to zip error"
          mv server.zip server.pyz
          cp server.pyz ..

      - name: upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          artifacts: '*.mcdr,*.pyz'
