name: build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          cd chatbridgee

          zip -r chatbridgee * || echo "build to zip error"
          mv chatbridgee.zip chatbridgee.mcdr
          cp chatbridgee.mcdr ..

          cd ..
          cp ../server.py __main__.py
          zip -r server server || echo "build to zip error"
          mv server.zip server.pyz

          cd plugins
          zip -r plugins * || echo "build to zip e rror"
          cp plugins.zip ..

      - name: upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          artifacts: '*.mcdr,*.pyz,*.zip'
